# Stage 1: Build the React app
FROM node:20 as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2: Serve the built React app using a lightweight server
FROM nginx:alpine

# Copy the built app from the previous stage
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 for serving the app
EXPOSE 8000:8000

# Start Nginx to serve the app
CMD ["nginx", "-g", "daemon off;"]
